services:
  db:
    image: postgres:15-alpine
    container_name: bts-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bugtracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: bts-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    volumes:
      - ./docker-config/pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - db

volumes:
  postgres_data: