spring.application.name=bug-tracking-api

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bugtracker
spring.datasource.username=user
spring.datasource.password=password

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true