name: CI Build

on:
  push:
    branches: [main, dev]
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make mvnw executable
        working-directory: backend
        run: chmod +x mvnw

      - name: Build and test
        working-directory: backend
        run: ./mvnw clean verify